org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false

android.useAndroidX=true
android.enableJetifier=false
android.suppressUnsupportedCompileSdk=35

# Reproducible builds
android.enableSourceSetPathsMap=true
android.experimental.cacheCompileLibResources=true
android.experimental.enableNewResourceShrinker.preciseShrinking=true
